# GERMAN – DEUTSCH // HOME
nav:
    - Hauptseite: index.md
    - Über Baslamo: about.md
    - Lernen:
        - Anleitung: de/guide
        - Nachschlagewerk: reference.md
        - Worterbüch: https://baslamo.miraheze.org/wiki/Main_Page
    - Discord: https://discord.gg/JhCT82B2Ts
    - Übersetzungen:
        - English: ../
        - Deutsch: /de/
        # - Français: ./fr/
        #- Español: ./es/