# DEUTSCH // HOME
nav:
    - Hauptseite: index.md
    - Über Baslamo: about.md
    - Anleitung: de/guide/
    - Worterbüch: ./dictionary/
    - Discord: https://discord.gg/JhCT82B2Ts
    - Übersetzungen:
        - English: ../
        - Deutsch: ./de/
        - Español: ./es/
        - Français: ./fr/
        - 日本語: ./ja/
        - 한국어: ./ko/
        - Русский: ./ru/
        - 中文: ./zh/