# ENGLISH // HOME
nav:
    - Home    - About:
    - Guide:
    - Dictionary:
    - Discord:
  - 
    Translations:
        - English:
        - Deutsch:
        - Español:
        - Français:
        - 日本語:
        - 한국어:
        - Русский:
        - 中文:
