# SPANISH – ESPAÑOL // HOME
nav:
    - Home: index.md
    - About: about.md
    - Learn:
        - Guide: es/guide
        - Reference: reference.md
        - Dictionary: https://baslamo.miraheze.org/wiki/Main_Page
    - Discord: https://discord.gg/JhCT82B2Ts
    - Translations:
        - English: ../
        - Deutsch: ./de/
        # - Français: ./fr/
        - Español: /es/