# ENGLISH // HOME
nav:
    0:
Home: Home
    1:
About: About
    2:
Guide: Guide
    3: [ ]
    Dictionary: Dictionary
Dictionary:
    - Discord: Discord
        #- Translations:
        #- English: ../
        #- Deutsch: ./de/
        #- Français: ./fr/
        #- Español: ./es/