# SPANISH – ESPAÑOL // GUIDE
nav:
    - Guide Index: ./guide/index.md
    - Lesson 1 — Pronunciation: ./guide/1_pronunciation.md
    - Lesson 2 — Sentences: ./guide/2_sentences.md
    - Lesson 3 — Derivation: ./guide/3_derivation.md
    - Lesson 4 — Tense and Aspect: ./guide/4_tense_and_aspect.md
    - Lesson 5 — Correlatives: ./guide/5_correlatives.md
    - Lesson 6 — Harder sentences: ./guide/6_hard_sentences.md
    - Lesson 7 — Proper Nouns: ./guide/7_proper_nouns.md
    - Lesson 8 — Introduce yourself: ./guide/8_introduction_exercise.md