# ENGLISH // HOME
nav:
    - Home: index.md
    - About: about.md
    - Guide: fr/guide
    -     #- Reference: reference.md
Dictionary: ./dictionary/
    - Discord: https://discord.gg/JhCT82B2Ts
        #- Translations:
        #- English: ../
        #- Deutsch: ./de/
        #- Français: ./fr/
        #- Español: ./es/